###########################################################
### Beautiful Jekyll Config - Rice Philharmonics
###########################################################

############################
# --- Required options --- #
############################

# Name of website
title: The Rice Philharmonics

# Your name to show in the footer
author: Phils

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About: "about"
  Members: "members"
  Auditions: "auditions"
  Media: "media"
  Book Us!: "https://docs.google.com/forms/d/e/1FAIpQLSf9WKgxZrQroKblc7k8FRaAFvB76R0U6dvr3LiUFPmmgfmBZg/viewform"

################
# --- Logo --- #
################

# Image to show in the navigation bar
title-img: /assets/img/PHILS LOGO NO RICE.PNG
round-avatar: false

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "ricephilharmonics@gmail.com"
  rss: true
  facebook: RicePhilharmonics
  youtube: "@RicePhilharmonics"
  instagram: ricephilharmonics

###########################
# --- General options --- #
###########################

# Add the website title to the title of every page
title-on-all-pages: true

# The keywords to associate with your website, for SEO purposes
keywords: "rice, phils, philharmonics, acapella, university, singing, music"

######################################
# --- Colors --- #
######################################

page-col: "#FFFFFF"
text-col: "#25272c"
link-col: "#008AFF"
hover-col: "#005fb7"
navbar-col: "#FFFFFF"
navbar-text-col: "#25272c"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

################
# --- Misc --- #
################

# Ruby Date Format
date_format: "%B %-d, %Y"

# Output options
timezone: "America/Chicago"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap